@base=http://0.0.0.0:8080/quick-scan-api
@auth_token=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJxdWljay1zY2FuLWFwaSIsInN1YiI6InVzZXItYXV0aCIsImF1ZCI6InF1aWNrLXNjYW4tY2xpZW50IiwidXNlcl9pZCI6IjAxOTU0YjBkLWY3NTYtNzQ2Ni1iMjFlLTk3MjJkMDE2ODM1MCIsImV4cCI6MTc0MTMyNTc3Mn0.a5jG7uAdopuiCRWDwrxX3CBkrK7S5t4tdoA2fVS3SA1KXB4IaNVVreYoGytmMeHjemWkfjLQ1_KdlEksNxnS_A

###
# @name=CreateAccount
POST {{base}}/account HTTP/1.1
Content-Type: application/json

{
    "username": "FooBar",
    "first_name": "Zab",
    "last_name": "Baz",
    "password": "FooBarZaa"
}

###
# @name=GetAccount
GET {{base}}/auth/account HTTP/1.1
Authorization: Bearer {{auth_token}}

###
# @name=LoginAccount
POST {{base}}/account/login HTTP/1.1
Content-Type: application/json

{
    "username": "FooBar",
    "password": "FooBarZaa"
}
